### ISSUE TITLE
Need to specify this firmware is for FAT formatted drives

### ISSUE THREAD

**Issue by shoon** [brahimmachkouri/ioddfirmware#1]
If you have an NTFS formatted drive and follow these procedures you'll get the following text on the LCD "1st Partition:" and the device will not respond. 

If you download the firmware with the "N" notation (iODD_2531_user_fw_writer_04(R1600N)_x86) and install, the NTFS formatted drive will work

**Comment by brahimmachkouri** [comment]
I've specified it already in this sentence : "Run the firmware writer iODD2531_user_fw_writer_02(R1288F)_x86.EXE as administrator (it's the firmware for FAT/exFAT)", but I've added your precisions. Thank you for that. :)
